# Generated by Django 3.2.13 on 2022-11-16 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0006_auto_20221116_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='like_review_users',
            field=models.ManyToManyField(default=0, related_name='like_user_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
