# Generated by Django 3.2.13 on 2022-11-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reg_no',
        ),
        migrations.RemoveField(
            model_name='user',
            name='university',
        ),
        migrations.AddField(
            model_name='user',
            name='prefer_genre',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
